export const environment = {
  production: true,
  accessories: 'accessories',
  aircraftRoute: 'aircraft-classes',
  aircraftModelsRoute: 'aircraft-models',
  aircraftModelDetailRoute: 'aircraft-model-detail',
  factoryRoute: 'factory',
  reviewsRoute: 'reviews',
  distributorsRoute: 'distributors',
  contactUsRoute: 'contact-us',
  whoMadeThisWebsiteRoute: 'who-made-this-website',
  thanhGuongRoute: 'thanh-guong',
  remoteHost: 'falcao5.ddns.net',
  // remoteHost: 'localhost',
  remotePort: '5294',
  // remotePort: '8000',
  remoteApiPrefix: 'api',
  aircraftAccessoriesRemote: 'aircraftmodelaccessories',
  aircraftClassRemoteRoute: 'aircraftclasses',
  aircraftModelRemoteRoute: 'aircraftmodels',
  aircraftVersionRemoteRoute: 'aircraftversions',
  getAircraftModelsByClass: 'get_aircraft_models_by_class',
  getAircraftVersionsByModel: 'get_aircraft_versions_by_model',
  contactUs: 'contactus',
  reviewsRouteRemote: 'reviews',
  distributorsRouteRemote: 'distributors',
  solitary_mode: true,
};
